(ns pizza.pizza-test
  (:require [cljs.test :refer-macros [deftest is testing run-tests]]
            [clojure.set :refer [superset?]]
            [pizza.core :refer [bake]]
            [pizza.recipes.neapolitan :as neapolitan]
            [pizza.recipes.sicilian :as sicilian]
            [pizza.recipes.pan :as pan]
            [pizza.recipes.new-york :as new-york]
            [pizza.schema.pizza :refer [pizza-keys]]))

(deftest neapolitan-dry-test
  (testing "neapolitan has minimal keys"
    (is (superset? (set (keys neapolitan/defaults)) pizza-keys))
    (is (superset? (set (keys sicilian/defaults)) pizza-keys))
    (is (superset? (set (keys pan/defaults)) pizza-keys))
    (is (superset? (set (keys new-york/defaults)) pizza-keys)))

  (testing "neapolitan with fresh yeast"
    (let [pizza (bake "neapolitan" 4 230 "dry")]
      (is (= (:type pizza) "neapolitan"))
      (is (= (:salt pizza) 16.4))
      (is (= (:grams-per-pizza pizza) 230))
      (is (= (:number pizza) 4))
      (is (= (:oil pizza) nil))
      (is (= (:oil-percentage pizza) nil))
      (is (= (:semolina pizza) nil))
      (is (= (:yeast-type pizza) "dry"))
      (is (= (:salt-percentage pizza) 0.0178261))
      (is (= (:yeast pizza) 0.4))
      (is (= (:total-weight pizza) 920))
      (is (= (:flour pizza) 547))
      (is (= (:sugar pizza) nil))
      (is (= (:sugar-percentage pizza) nil))
      (is (= (:water-share pizza) 65))
      (is (= (:water pizza) 356))
      (is (= (:semolina-percentage pizza) nil))))
  (testing "neapolitan with fresh yeast"
    (let [pizza (bake "neapolitan" 4 230 "fresh")]
      (is (= (:type pizza) "neapolitan"))
      (is (= (:salt pizza) 16.4))
      (is (= (:grams-per-pizza pizza) 230))
      (is (= (:number pizza) 4))
      (is (= (:oil pizza) nil))
      (is (= (:oil-percentage pizza) nil))
      (is (= (:semolina pizza) nil))
      (is (= (:yeast-type pizza) "fresh"))
      (is (= (:salt-percentage pizza) 0.0178261))
      (is (= (:yeast pizza) 1.1))
      (is (= (:total-weight pizza) 920))
      (is (= (:flour pizza) 547))
      (is (= (:sugar pizza) nil))
      (is (= (:sugar-percentage pizza) nil))
      (is (= (:water-share pizza) 65))
      (is (= (:water pizza) 356))
      (is (= (:semolina-percentage pizza) nil)))))

(deftest new-york-dry-test
  (testing "new york style with dry yeast"
    (let [pizza (bake "new-york" 4 230 "dry")]
      (is (= (:type pizza) "new-york"))
      (is (= (:salt pizza) 10.9))
      (is (= (:grams-per-pizza pizza) 230))
      (is (= (:number pizza) 4))
      (is (= (:oil pizza) 16.3))
      (is (= (:oil-percentage pizza) 0.0177173913))
      (is (= (:semolina pizza) nil))
      (is (= (:yeast-type pizza) "dry"))
      (is (= (:salt-percentage pizza) 0.0118478))
      (is (= (:yeast pizza) 1.5))
      (is (= (:total-weight pizza) 920))
      (is (= (:flour pizza) 545))
      (is (= (:sugar pizza) 3.3))
      (is (= (:sugar-percentage pizza) 0.0036))
      (is (= (:water-share pizza) 63))
      (is (= (:water pizza) 343))
      (is (= (:semolina-percentage pizza) nil))))
  (testing "new york style with fresh yeast 3 pizzas"
    (let [pizza (bake "new-york" 3 230 "fresh")]
      (is (= (:type pizza) "new-york"))
      (is (= (:salt pizza) 8.2))
      (is (= (:grams-per-pizza pizza) 230))
      (is (= (:number pizza) 3))
      (is (= (:oil pizza) 12.2))
      (is (= (:oil-percentage pizza) 0.0177173913))
      (is (= (:semolina pizza) nil))
      (is (= (:yeast-type pizza) "fresh"))
      (is (= (:salt-percentage pizza) 0.0118478))
      (is (= (:yeast pizza) 3.5))
      (is (= (:total-weight pizza) 690))
      (is (= (:flour pizza) 407))
      (is (= (:sugar pizza) 2.5))
      (is (= (:sugar-percentage pizza) 0.0036))
      (is (= (:water-share pizza) 63))
      (is (= (:water pizza) 256))
      (is (= (:semolina-percentage pizza) nil))))
  (testing "new york style with fresh yeast"
    (let [pizza (bake "new-york" 4 230 "fresh")]
      (is (= (:type pizza) "new-york"))
      (is (= (:salt pizza) 10.9))
      (is (= (:grams-per-pizza pizza) 230))
      (is (= (:number pizza) 4))
      (is (= (:oil pizza) 16.3))
      (is (= (:oil-percentage pizza) 0.0177173913))
      (is (= (:semolina pizza) nil))
      (is (= (:yeast-type pizza) "fresh"))
      (is (= (:salt-percentage pizza) 0.0118478))
      (is (= (:yeast pizza) 4.6))
      (is (= (:total-weight pizza) 920))
      (is (= (:flour pizza) 543))
      (is (= (:sugar pizza) 3.3))
      (is (= (:sugar-percentage pizza) 0.0036))
      (is (= (:water-share pizza) 63))
      (is (= (:water pizza) 342))
      (is (= (:semolina-percentage pizza) nil)))))

(deftest sicilian-test
  (testing "sicilian dry test"
    (let [pizza (bake "sicilian" 1 271 "dry")]
      (is (= (:type pizza) "sicilian"))
      (is (= (:salt pizza) 3))
      (is (= (:grams-per-pizza pizza) 271))
      (is (= (:number pizza) 1))
      (is (= (:oil pizza) 7))
      (is (= (:oil-percentage pizza) 0.02583))
      (is (= (:semolina pizza) 34))
      (is (= (:yeast-type pizza) "dry"))
      (is (= (:salt-percentage pizza) 0.01107))
      (is (= (:yeast pizza) 0.9))
      (is (= (:total-weight pizza) 271))
      (is (= (:flour pizza) 121))
      (is (= (:sugar pizza) 3))
      (is (= (:sugar-percentage pizza) 0.01107))
      (is (= (:water-share pizza) 66))
      (is (= (:water pizza) 102))
      (is (= (:semolina-percentage pizza) 0.22))))
  (testing "sicilian fresh test"
    (let [pizza (bake "sicilian" 1 271 "fresh")]
      (is (= (:type pizza) "sicilian"))
      (is (= (:salt pizza) 3))
      (is (= (:grams-per-pizza pizza) 271))
      (is (= (:number pizza) 1))
      (is (= (:oil pizza) 7))
      (is (= (:oil-percentage pizza) 0.02583))
      (is (= (:semolina pizza) 34))
      (is (= (:yeast-type pizza) "fresh"))
      (is (= (:salt-percentage pizza) 0.01107))
      (is (= (:yeast pizza) 2.2))
      (is (= (:total-weight pizza) 271))
      (is (= (:flour pizza) 120))
      (is (= (:sugar pizza) 3))
      (is (= (:sugar-percentage pizza) 0.01107))
      (is (= (:water-share pizza) 66))
      (is (= (:water pizza) 102))
      (is (= (:semolina-percentage pizza) 0.22))))
  (testing "sicilian fresh test double dish"
    (let [pizza (bake "sicilian" 2 540 "fresh")]
      (is (= (:type pizza) "sicilian"))
      (is (= (:salt pizza) 12))
      (is (= (:grams-per-pizza pizza) 540))
      (is (= (:number pizza) 2))
      (is (= (:oil pizza) 27.9))
      (is (= (:oil-percentage pizza) 0.02583))
      (is (= (:semolina pizza) 135))
      (is (= (:yeast-type pizza) "fresh"))
      (is (= (:salt-percentage pizza) 0.01107))
      (is (= (:yeast pizza) 8.8))
      (is (= (:total-weight pizza) 1080))
      (is (= (:flour pizza) 479))
      (is (= (:sugar pizza) 12))
      (is (= (:sugar-percentage pizza) 0.01107))
      (is (= (:water-share pizza) 66))
      (is (= (:water pizza) 405))
      (is (= (:semolina-percentage pizza) 0.22))))

  (testing "lauermän pan pizza with fresh yeast for 2"
    (let [pizza (bake "pan" 3 240 "fresh")]
      (is (= (:type pizza) "pan"))
      (is (= (:salt pizza) 8.4))
      (is (= (:grams-per-pizza pizza) 240))
      (is (= (:number pizza) 3))
      (is (= (:oil pizza) 10))
      (is (= (:oil-percentage pizza) 0.0139082058))
      (is (= (:semolina pizza) nil))
      (is (= (:yeast-type pizza) "fresh"))
      (is (= (:salt-percentage pizza) 0.011682893))
      (is (= (:yeast pizza) 1.7))
      (is (= (:total-weight pizza) 720))
      (is (= (:flour pizza) 419))
      (is (= (:sugar pizza) 8.4))
      (is (= (:sugar-percentage pizza) 0.011682893))
      (is (= (:water-share pizza) 65))
      (is (= (:water pizza) 272))
      (is (= (:semolina-percentage pizza) nil))))
  (testing "lauermän pan pizza with dry yeast for 2"
    (let [pizza (bake "pan" 3 240 "dry")]
      (is (= (:type pizza) "pan"))
      (is (= (:salt pizza) 8.4))
      (is (= (:grams-per-pizza pizza) 240))
      (is (= (:number pizza) 3))
      (is (= (:oil pizza) 10))
      (is (= (:oil-percentage pizza) 0.0139082058))
      (is (= (:semolina pizza) nil))
      (is (= (:yeast-type pizza) "dry"))
      (is (= (:salt-percentage pizza) 0.011682893))
      (is (= (:yeast pizza) 0.7))
      (is (= (:total-weight pizza) 720))
      (is (= (:flour pizza) 420))
      (is (= (:sugar pizza) 8.4))
      (is (= (:sugar-percentage pizza) 0.011682893))
      (is (= (:water-share pizza) 65))
      (is (= (:water pizza) 273))
      (is (= (:semolina-percentage pizza) nil)))))
